# Auto-generated by scripts/gen_srcs.sh

INCDIR = include
SRCDIR = src

HDRS = \
	include/ft_malloc.h


SRCS = \
	src/free.c \
	src/lib/arena.c \
	src/lib/chunk.c \
	src/lib/system.c \
	src/lib/zone.c \
	src/malloc.c \
	src/realloc.c \
	src/show_alloc_mem.c
