#!/bin/sh
# Generate srcs.mk containing the list of all source and header files.
# Usage: ./scripts/gen_srcs.sh [src_dir] [include_dir]

set -e

DEST="srcs.mk"
SRCDIR="${1:-src}"
INCDIR="${2:-include}"

if [ ! -d "$SRCDIR" ] || [ ! -d "$INCDIR" ]; then
    echo "Error: Invalid SRCDIR ($SRCDIR) or INCDIR ($INCDIR). Must be a directory." >&2
    exit 1
fi

echo "Generating $DEST..."

{
    echo "# Auto-generated by scripts/gen_srcs.sh"
    echo ""
    echo "INCDIR = $INCDIR"
    echo "SRCDIR = $SRCDIR"
    echo ""
    
    echo "HDRS = \\"
    # Find all .h files, sort them, indent with a tab, and append a backslash to all but the last line
    find "$INCDIR" -type f -name '*.h' | sort | sed 's/^/	/' | sed '$!s/$/ \\/'
    echo ""
    echo ""
    
    echo "SRCS = \\"
    # Find all .c files, sort them, indent with a tab, and append a backslash to all but the last line
    find "$SRCDIR" -type f -name '*.c' | sort | sed 's/^/	/' | sed '$!s/$/ \\/'
    echo ""
} > "$DEST"

echo "Done. $DEST created."
